[project]
name = "pnpm-react-fastapi"
version = "0.1.0"
description = "This is the workspace root."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.8",
    "uvicorn>=0.40.0",
]

[tool.uv.workspace]
members = ["core", "infra", "application"]
